### PR TITLE
[WIP] Enable php 8 in composer deps & travis matrix

### PR DESCRIPTION
**Pull request by rvdbogerd**

### CODE REVIEW

**Comment by goetas** [comment]
hi, can you please let me know when this is out of WIP stage?

**Comment by rvdbogerd** [comment]
> hi, can you please let me know when this is out of WIP stage?

I'd like to, but then we need to upgrade a couple of other libraries too (soap-common, soap-reader, wsdl2php, etc.)

I might have some time between 21-28 october, will try to do some fixes then, hopefully you'll have time to quickly review and approve then.

**Comment by rvdbogerd** [comment]
btw, what is the status of these static analysis checks? it seems they were already failing?

**Comment by sobernt** [comment]
Hello!
what is the status of this pull request?

**Comment by goetas** [comment]
> btw, what is the status of these static analysis checks? it seems they were already failing?

yea, when i started it, i dind not have the time to complete it... i was running tests only locally

**Comment by goetas** [comment]
however, i'm finger crossing that the lib was good enough for php 8 to run smoothly

**Comment by goetas** [comment]
recently also travisci got awful... probably is the time to migrate to github actions

**Pull request merged**
