### PR TITLE
Add support for application/soap+xml content types.

### PR DESCRIPTION
**Pull request by jenkoian**

### CODE REVIEW

**Comment by goetas** [comment]
Am I wrong? Do you have a 1.1 server that uses the application/soap+xml header?

**Comment by jenkoian** [comment]
@goetas thanks for the swift reply! You're right, it's a 1.2 service. Do you happen to know how far away from merge #6 is? Wondering if you would merge this now (as it's the only thing stopping the service I'm integrating working with the current release)?

**Comment by goetas** [comment]
At the moment #6 will not work if in your wsdl you have defined both soap 1.1 and soap 1.2 definitions.

If you have only soap 1.2, then probably is safe to merge. If this is the case i suggest you to use directly the branch via composer.

**Comment by goetas** [comment]
You can see on #6 what is missing

**Comment by jenkoian** [comment]
Yeah the service I'm integrating with is 1.2 only. When you say use branch, are you saying you are happy to merge it but not yet tag it, or do you want me to use my fork directly?

**Comment by goetas** [comment]
> When you say use branch, are you saying you are happy to merge it but not yet tag it, or do you want me to use my fork directly?

To use it you have at least two options: 

- you can use your fork (suggested in case you will have to not-fix things=
- use `"goetas-webservices":"soap-12-dev as 0.2.0"` into your composer.json file

**Comment by jenkoian** [comment]
@goetas ah I see what you mean, so the 1.2 branch you are working on is ready except for the case where you need to support both? If so, I will try using just that branch then yeah fall back to my own fork 👍

**Comment by goetas** [comment]
:) good luck!

**Comment by jenkoian** [comment]
Am using the soap-12 branch successfully, cheers! 👍

**Comment by goetas** [comment]
i suggest you to fork the repo and use your copy. do not exclude updates on the branch

**Comment by jenkoian** [comment]
@goetas fair - if I re-open this PR, would you consider a merge? (or I can change to what you did in the 1.2 branch to basically check the content type is xml in any capacity). Maintaining my own fork for such a minor tweak seems overkill.

**Comment by goetas** [comment]
as siad, this cant be merged. 

> Maintaining my own fork for such a minor tweak seems overkill.

it is just to avoid unexpected effect on your side in case i update my branch

**Comment by jenkoian** [comment]
> as siad, this cant be merged.

Sorry, may have missed this, do you mind explaining why again? It's just changing the way it checks the content type? 

> it is just to avoid unexpected effect on your side in case i update my branch

Yeah understand that, just trying to avoid it somehow :)

**Comment by goetas** [comment]
>Sorry, may have missed this, do you mind explaining why again? It's just changing the way it checks the content type? 

if i merge this, will introduce a partial soap 1.2 support (that is not yer implemented)

**Comment by jenkoian** [comment]
Ah yeah, I guess, but partial support is just what I need 😝 

No worries, I'll fork 👍  cheers for your help

**Pull request closed without merging**
